version: '3'

services:
  poll:
    build: ./poll
    restart: always
    ports:
      - 5000:80
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    hostname: redis
    ports:
      - "6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: always
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - back-tier
    depends_on:
      - redis
      - db

  db:
    image: postgres:16
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgres/data

  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - result-tier
    depends_on:
      - db

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
